<?php
$veiculos = [
    [
        'marca' => 'Ford',
        'modelo' => 'Mustang',
        'ano_lancamento' => 2020,
        'ano_fabricacao' => 2019,
        'versao' => 'GT',
        'cor' => 'Azul',
        'blindado' => 'N', 
        'km' => 5000,
        'descricao_inicial' => 'Carro esportivo rápido e elegante',
        'descricao_completa' => 'Um carro de alto desempenho, perfeito para quem gosta de velocidade e estilo.',
        'preco' => 150000, 
        'anuncio_liberado' => 'N',
        'imagem_anuncio' => '../imgs/anuncio/' . strtolower('mustang') . '.jpg',
        'id_usuario' => 8
    ],
    [
        'marca' => 'Chevrolet',
        'modelo' => 'Camaro',
        'ano_lancamento' => 2021,
        'ano_fabricacao' => 2020,
        'versao' => 'SS',
        'cor' => 'Vermelho',
        'blindado' => 'S',
        'km' => 2000,
        'descricao_inicial' => 'O Camaro é um carro potente e de destaque.',
        'descricao_completa' => 'Um carro esportivo com muito estilo, ideal para quem gosta de chamar atenção.',
        'preco' => 250000,
        'anuncio_liberado' => 'N',
        'imagem_anuncio' => '../imgs/anuncio/' . strtolower('camaro') . '.jpg',
        'id_usuario' => 8
    ],
    [
        'marca' => 'Tesla',
        'modelo' => 'Model S',
        'ano_lancamento' => 2022,
        'ano_fabricacao' => 2021,
        'versao' => 'Plaid',
        'cor' => 'Branco',
        'blindado' => 'N',
        'km' => 300,
        'descricao_inicial' => 'Carro elétrico de alto desempenho.',
        'descricao_completa' => 'Um dos carros elétricos mais rápidos do mercado, com tecnologia de ponta.',
        'preco' => 500000,
        'anuncio_liberado' => 'N',
        'imagem_anuncio' => '../imgs/anuncio/' . strtolower('model s') . '.jpg',
        'id_usuario' => 8
    ],
    [
        'marca' => 'Chevrolet',
        'modelo' => 'Corvette',
        'ano_lancamento' => 2020,
        'ano_fabricacao' => 2019,
        'versao' => 'Z06',
        'cor' => 'Amarelo',
        'blindado' => 'N',
        'km' => 1000,
        'descricao_inicial' => 'Corvette esportivo e elegante.',
        'descricao_completa' => 'Um carro esportivo com alto desempenho e estilo.',
        'preco' => 180000,
        'anuncio_liberado' => 'N',
        'imagem_anuncio' => '../imgs/anuncio/' . strtolower('corvette') . '.jpg',
        'id_usuario' => 8
    ],
    [
        'marca' => 'BMW',
        'modelo' => 'X5',
        'ano_lancamento' => 2019,
        'ano_fabricacao' => 2018,
        'versao' => 'xDrive40i',
        'cor' => 'Preto',
        'blindado' => 'S',
        'km' => 8000,
        'descricao_inicial' => 'SUV de luxo e segurança.', 
        'descricao_completa' => 'Um SUV de luxo com blindagem para proteção adicional.',
        'preco' => 280000,
        'anuncio_liberado' => 'N',
        'imagem_anuncio' => '../imgs/anuncio/' . strtolower('x5') . '.jpg',
        'id_usuario' => 8
    ],
    [
        'marca' => 'Toyota',
        'modelo' => 'Land Cruiser',
        'ano_lancamento' => 2021,
        'ano_fabricacao' => 2020,
        'versao' => 'GXR',
        'cor' => 'Branco',
        'blindado' => 'S',
        'km' => 12000,
        'descricao_inicial' => 'SUV resistente e confiável.', 
        'descricao_completa' => 'Um SUV com resistência e confiabilidade para qualquer terreno.',
        'preco' => 350000,
        'anuncio_liberado' => 'N',
        'imagem_anuncio' => '../imgs/anuncio/' . strtolower('land cruiser') . '.jpg',
        'id_usuario' => 8
    ],
    [
        'marca' => 'Audi',
        'modelo' => 'Q7',
        'ano_lancamento' => 2020,
        'ano_fabricacao' => 2019,
        'versao' => 'S-Line',
        'cor' => 'Prata',
        'blindado' => 'N',
        'km' => 6000,
        'descricao_inicial' => 'SUV de luxo com ótimo desempenho.',
        'descricao_completa' => 'Um SUV de luxo que combina estilo e desempenho.',
        'preco' => 240000,
        'anuncio_liberado' => 'N',
        'imagem_anuncio' => '../imgs/anuncio/' . strtolower('q7') . '.jpg',
        'id_usuario' => 8
    ],
    [
        'marca' => 'Mercedes-Benz',
        'modelo' => 'G-Class',
        'ano_lancamento' => 2022,
        'ano_fabricacao' => 2021,
        'versao' => 'G63 AMG',
        'cor' => 'Preto',
        'blindado' => 'S',
        'km' => 200,
        'descricao_inicial' => 'SUV de alto luxo e segurança.',
        'descricao_completa' => 'Um SUV premium com alta performance e segurança.',
        'preco' => 550000,
        'anuncio_liberado' => 'N',
        'imagem_anuncio' => '../imgs/anuncio/' . strtolower('g-class') . '.jpg',
        'id_usuario' => 8
    ],
    [
        'marca' => 'Land Rover',
        'modelo' => 'Range Rover',
        'ano_lancamento' => 2018,
        'ano_fabricacao' => 2017,
        'versao' => 'Vogue SE',
        'cor' => 'Verde',
        'blindado' => 'N',
        'km' => 10000,
        'descricao_inicial' => 'SUV de luxo e tradição.',
        'descricao_completa' => 'Um SUV que oferece conforto e luxo com estilo.',
        'preco' => 300000,
        'anuncio_liberado' => 'N',
        'imagem_anuncio' => '../imgs/anuncio/' . strtolower('range rover') . '.jpg',
        'id_usuario' => 8
    ],
    [
        'marca' => 'Ferrari',
        'modelo' => '488',
        'ano_lancamento' => 2019,
        'ano_fabricacao' => 2018,
        'versao' => 'GTB',
        'cor' => 'Vermelho',
        'blindado' => 'N',
        'km' => 5000,
        'descricao_inicial' => 'Esportivo de alto desempenho',
        'descricao_completa' => 'Ferrari 488 GTB, esportivo com grande potência.',
        'preco' => 380000,
        'anuncio_liberado' => 'N',
        'imagem_anuncio' => '../imgs/anuncio/' . strtolower('488') . '.jpg',
        'id_usuario' => 8
    ],
    [
        'marca' => 'Lamborghini',
        'modelo' => 'Huracan',
        'ano_lancamento' => 2021,
        'ano_fabricacao' => 2020,
        'versao' => 'LP 610-4',
        'cor' => 'Laranja',
        'blindado' => 'N',
        'km' => 1000,
        'descricao_inicial' => 'Lamborghini esportivo',
        'descricao_completa' => 'Lamborghini Huracan, um esportivo icônico.',
        'preco' => 450000,
        'anuncio_liberado' => 'N',
        'imagem_anuncio' => '../imgs/anuncio/' . strtolower('huracan') . '.jpg',
        'id_usuario' => 8
    ],
    [
        'marca' => 'Rolls-Royce',
        'modelo' => 'Phantom',
        'ano_lancamento' => 2018,
        'ano_fabricacao' => 2017,
        'versao' => 'Standard',
        'cor' => 'Preto',
        'blindado' => 'S',
        'km' => 3000,
        'descricao_inicial' => 'Luxo e segurança',
        'descricao_completa' => 'Rolls-Royce Phantom, luxo com blindagem.',
        'preco' => 600000,
        'anuncio_liberado' => 'N',
        'imagem_anuncio' => '../imgs/anuncio/' . strtolower('phantom') . '.jpg',
        'id_usuario' => 8
    ],
    [
        'marca' => 'Bentley',
        'modelo' => 'Continental GT',
        'ano_lancamento' => 2020,
        'ano_fabricacao' => 2019,
        'versao' => 'W12',
        'cor' => 'Azul',
        'blindado' => 'N',
        'km' => 7000,
        'descricao_inicial' => 'Luxo e desempenho',
        'descricao_completa' => 'Bentley Continental GT, um clássico de luxo.',
        'preco' => 420000,
        'anuncio_liberado' => 'N',
        'imagem_anuncio' => '../imgs/anuncio/' . strtolower('continental gt') . '.jpg',
        'id_usuario' => 8
    ],
    [
        'marca' => 'Porsche',
        'modelo' => '911 Carrera',
        'ano_lancamento' => 2019,
        'ano_fabricacao' => 2018,
        'versao' => '4S',
        'cor' => 'Prata',
        'blindado' => 'N',
        'km' => 15000,
        'descricao_inicial' => 'Clássico esportivo',
        'descricao_completa' => 'Porsche 911 Carrera, um clássico atemporal.',
        'preco' => 360000,
        'anuncio_liberado' => 'N',
        'imagem_anuncio' => '../imgs/anuncio/' . strtolower('911 carrera') . '.jpg',
        'id_usuario' => 8
    ],
    [
        'marca' => 'Jaguar',
        'modelo' => 'F-Type',
        'ano_lancamento' => 2019,
        'ano_fabricacao' => 2018,
        'versao' => 'R-Dynamic',
        'cor' => 'Branco',
        'blindado' => 'N',
        'km' => 12000,
        'descricao_inicial' => 'Jaguar esportivo',
        'descricao_completa' => 'Jaguar F-Type, um esportivo com estilo.',
        'preco' => 330000,
        'anuncio_liberado' => 'N',
        'imagem_anuncio' => '../imgs/anuncio/' . strtolower('f-type') . '.jpg',
        'id_usuario' => 8
    ],
    [
        'marca' => 'Tesla',
        'modelo' => 'Model S',
        'ano_lancamento' => 2020,
        'ano_fabricacao' => 2019,
        'versao' => 'Performance',
        'cor' => 'Branco',
        'blindado' => 'N',
        'km' => 10000,
        'descricao_inicial' => 'Carro elétrico de alto desempenho',
        'descricao_completa' => 'Tesla Model S, um carro elétrico com grande alcance.',
        'preco' => 400000,
        'anuncio_liberado' => 'N',
        'imagem_anuncio' => '../imgs/anuncio/' . strtolower('model s') . '.jpg',
        'id_usuario' => 8
    ],
    [
        'marca' => 'Chevrolet',
        'modelo' => 'Onix',
        'ano_lancamento' => 2021,
        'ano_fabricacao' => 2020,
        'versao' => 'LTZ',
        'cor' => 'Prata',
        'blindado' => 'N',
        'km' => 10000,
        'descricao_inicial' => 'Compacto com ótimo custo-benefício',
        'descricao_completa' => 'Chevrolet Onix, compacto e econômico.',
        'preco' => 60000,
        'anuncio_liberado' => 'N',
        'imagem_anuncio' => '../imgs/anuncio/' . strtolower('onix') . '.jpg',
        'id_usuario' => 8
    ],
    [
        'marca' => 'Hyundai',
        'modelo' => 'HB20',
        'ano_lancamento' => 2021,
        'ano_fabricacao' => 2020,
        'versao' => 'Evolution',
        'cor' => 'Preto',
        'blindado' => 'N',
        'km' => 15000,
        'descricao_inicial' => 'Hyundai HB20, moderno e eficiente.',
        'descricao_completa' => 'Versão Evolution, com recursos de segurança avançados.',
        'preco' => 70000,
        'anuncio_liberado' => 'N',
        'imagem_anuncio' => '../imgs/anuncio/' . strtolower('hb20') . '.jpg',
        'id_usuario' => 8
    ],
    [
        'marca' => 'Fiat',
        'modelo' => 'Argo',
        'ano_lancamento' => 2020,
        'ano_fabricacao' => 2019,
        'versao' => 'Drive',
        'cor' => 'Vermelho',
        'blindado' => 'N',
        'km' => 20000,
        'descricao_inicial' => 'Fiat Argo, compacto e confortável.',
        'descricao_completa' => 'Fiat Argo Drive, com bom espaço interno e conforto.',
        'preco' => 65000,
        'anuncio_liberado' => 'N',
        'imagem_anuncio' => '../imgs/anuncio/' . strtolower('argo') . '.jpg',
        'id_usuario' => 8
    ],
    [
        'marca' => 'Volkswagen',
        'modelo' => 'Polo',
        'ano_lancamento' => 2021,
        'ano_fabricacao' => 2020,
        'versao' => 'Highline',
        'cor' => 'Azul',
        'blindado' => 'N',
        'km' => 12000,
        'descricao_inicial' => 'Volkswagen Polo, compacto com bom desempenho.',
        'descricao_completa' => 'Versão Highline, com ótima dirigibilidade e recursos modernos.',
        'preco' => 80000,
        'anuncio_liberado' => 'N',
        'imagem_anuncio' => '../imgs/anuncio/' . strtolower('polo') . '.jpg',
        'id_usuario' => 8
    ],
    [
        'marca' => 'Toyota',
        'modelo' => 'Corolla',
        'ano_lancamento' => 2021,
        'ano_fabricacao' => 2020,
        'versao' => 'XEi',
        'cor' => 'Branco',
        'blindado' => 'N',
        'km' => 8000,
        'descricao_inicial' => 'Toyota Corolla, o clássico sedã.',
        'descricao_completa' => 'Versão XEi, com excelente confiabilidade e eficiência.',
        'preco' => 95000,
        'anuncio_liberado' => 'N',
        'imagem_anuncio' => '../imgs/anuncio/' . strtolower('corolla') . '.jpg',
        'id_usuario' => 8
    ],
    [
        'marca' => 'Honda',
        'modelo' => 'Civic',
        'ano_lancamento' => 2021,
        'ano_fabricacao' => 2020,
        'versao' => 'Sport',
        'cor' => 'Cinza',
        'blindado' => 'N',
        'km' => 9000,
        'descricao_inicial' => 'Honda Civic, desportivo e estiloso.',
        'descricao_completa' => 'Versão Sport, com design moderno e ótimo desempenho.',
        'preco' => 92000,
        'anuncio_liberado' => 'N',
        'imagem_anuncio' => '../imgs/anuncio/' . strtolower('civic') . '.jpg',
        'id_usuario' => 8
    ],
   
];


?>
